allow_duplicate_keys = false
comments_min_spaces_from_content = 1
sequence_style = "block_style"
indent_mapping = 2
indent_offset = 2
indent_sequence = 4
none_representation = "~"
explicit_start = false
